name: Deploy API to Amazon ECR

on:
  push:
    branches: [ master ]
    paths: qeep_site/

env:
  DOCKERFILE: Dockerfile.api
  AWS_REGION: sa-east-1                          # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: turing/qeep_api
  FUNC_NAME: turing-qeep-api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: s3-deploy
      run: aws s3 sync ./qeep_site s3://turing-qeep-site
